USE CAllYourMom;

CREATE TABLE IF NOT EXISTS Users (
  id INTEGER(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  firstName VARCHAR(30) NOT NULL,
  lastName VARCHAR(30) NOT NULL,
  userName VARCHAR(20) NOT NULL,
  password VARCHAR(20) NOT NULL,
  address VARCHAR(255),
  telephone VARCHAR(20)
) engine=InnoDB;


CREATE TABLE IF NOT EXISTS Friendship (
id INTEGER(11) NOT NULL,
friendId INTEGER(11) NOT NULL
);



CREATE TABLE IF NOT EXISTS Events(
  id INTEGER(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  time VARCHAR(30) NOT NULL,
  title VARCHAR(30) NOT NULL,
  location VARCHAR(30) NOT NULL,
  friends_invited VARCHAR(100),
  friends_going VARCHAR(100),
  tags VARCHAR(30),
  description VARCHAR(300)
) engine=InnoDB;



CREATE TABLE IF NOT EXISTS Reminders(
  id INTEGER(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  time VARCHAR(30) NOT NULL,
  title VARCHAR(30) NOT NULL,
  location VARCHAR(30) NOT NULL
) engine=InnoDB;
  
  
CREATE TABLE IF NOT EXISTS Settings(
id INTEGER(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
theme boolean NOT NULL,
notification boolean NOT NULL,
sharing VARCHAR(30)

)



  







